from PyQt5 import QtCore, QtGui, QtWidgets
import csv

class Ui_StartWIndow(object):
    def setupUi(self, StartWIndow):
        StartWIndow.setObjectName("StartWIndow")
        StartWIndow.resize(1196, 654)
        StartWIndow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StartWIndow.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(StartWIndow)
        self.label.setGeometry(QtCore.QRect(30, 10, 621, 141))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(StartWIndow)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(StartWIndow)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 721, 98))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(StartWIndow)
        self.label_4.setGeometry(QtCore.QRect(40, 437, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Dyuthi")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        font.setFamily("Noto")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(StartWIndow)
        self.progressBar.setGeometry(QtCore.QRect(690, 30, 461, 23))
        self.update_progress()
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(StartWIndow)
        self.textBrowser.setGeometry(QtCore.QRect(40, 480, 651, 141))
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(StartWIndow)
        self.pushButton.setGeometry(QtCore.QRect(810, 290, 341, 91))
        font = QtGui.QFont()
        font.setFamily("Sarai")
        font.setPointSize(45)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(StartWIndow)
        self.label_6.setGeometry(QtCore.QRect(830, 400, 331, 41))
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(StartWIndow)
        self.pushButton_4.setGeometry(QtCore.QRect(830, 570, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(StartWIndow)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 480, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Sarai")
        font.setPointSize(36)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(StartWIndow)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 60, 461, 151))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(72)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(StartWIndow)
        self.label_5.setGeometry(QtCore.QRect(870, 220, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK KR")
        font.setPointSize(34)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.progressBar.raise_()
        self.textBrowser.raise_()
        self.label_6.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.label_5.raise_()

        self.retranslateUi(StartWIndow)
        QtCore.QMetaObject.connectSlotsByName(StartWIndow)

    def retranslateUi(self, StartWIndow):
        _translate = QtCore.QCoreApplication.translate
        StartWIndow.setWindowTitle(_translate("StartWIndow", "EngSquare"))
        self.label.setText(_translate("StartWIndow", "𝙴𝚗𝚐𝚂𝚚𝚞𝚊𝚛𝚎"))
        self.label_2.setText(_translate("StartWIndow", "The brand new way to learn English"))
        self.label_3.setText(_translate("StartWIndow", "Someone is sitting in the shade today because someone planted\n"
                                                       "a tree a long time ago.\n"
                                                       "\t\t\t                                  - Warren Buffett"))
        self.label_4.setText(_translate("StartWIndow", "Get in touch with our helpful team:"))
        self.textBrowser.setHtml(_translate("StartWIndow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Medium\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"tg://resolve?domain=engsquare\"><img src=\"sources/telegram_link.png\" /></a><a href=\"viber://chat?number=+79101139919\"><img src=\"sources/viber.png\" /></a><a href=\"https://vk.com/engsquare\"><img src=\"sources/vk.png\" /></a><a href=\"https://wa.me/79101139919\"><img src=\"sources/whatsapp.png\" /></a><a href=\"https://www.facebook.com/EngSquare-337729900402993\"><img src=\"sources/facebook.png\" /></a></p></body></html>"))
        self.pushButton.setText(_translate("StartWIndow", "START"))
        self.label_6.setText(_translate("StartWIndow", "your daily workout 😼"))
        self.pushButton_4.setText(_translate("StartWIndow", "Change your preferences ⚙️"))
        self.pushButton_2.setText(_translate("StartWIndow", "Vocabulary ⽕"))
        self.pushButton_3.setText(_translate("StartWIndow", "PLAY"))
        self.label_5.setText(_translate("StartWIndow", "the game 😻"))

    def update_progress(self):
        n, m = 0, 0
        with open('sources/vocabulary.csv', encoding="utf8") as f:
            reader = csv.reader(f, delimiter=';')
            for i in reader:
                n += float(i[2])
                m += 30
        if not m:
            m = 1
        self.progressBar.setProperty("value", int(n / m * 100))
